server:
  port: 80
spring:
  application:
    name: wechat-develop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

wechat:
  token: wechat123

redis:
  host: 127.0.0.1       #地址
  port: 6379            #端口
  auth:                 #密码
  max_active: 1024     #如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
  max_idle: 200        #控制一个pool最多有多少个状态为idle(空闲的)的jedis实例，默认值也是8。
  max_wait: 10000      #等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException；
  timeout: 10000
